"""Typed configuration compiled from workbook row xlsx_s2_0268."""

from dataclasses import dataclass

from strategies.workbook_parametric.config import WorkbookParametricConfig


@dataclass(frozen=True)
class XlsxS20268Config(WorkbookParametricConfig):
    source_registry_id: str = 'xlsx_s2_0268'
    family: str = 'phase5b_declarative'
    semantic_provenance: str = 'MODELLED_BASELINE_INTERPRETATION'
    contracts_applied: str = 'MODELLED_STANDARD_REGULAR_DIVERGENCE_V1;CONFIRMED_FRACTAL_2X2_V1;DIVERGENCE_LOOKBACK_60_V1;ACTION_PRECEDENCE_EXIT_REDUCE_ENTER_V1;REDUCE_HALF_CURRENT_V1'
    defaulted_parameters: str = 'divergence_side_bars=2;divergence_lookback=60'
    rule_spec_b64: str = 'eyJhY3Rpb25zIjpbeyJhY3Rpb24iOiJFWElUX0xPTkciLCJjb25kaXRpb24iOnsib3AiOiJwdWxzZSIsInZhbHVlIjoicDVmX3VwcGVyX2ZyYWN0YWwifSwiZnJhY3Rpb24iOjEuMCwicmVhc29uIjoicGhhc2U1ZiJ9LHsiYWN0aW9uIjoiRVhJVF9TSE9SVCIsImNvbmRpdGlvbiI6eyJvcCI6InB1bHNlIiwidmFsdWUiOiJwNWZfbG93ZXJfZnJhY3RhbCJ9LCJmcmFjdGlvbiI6MS4wLCJyZWFzb24iOiJwaGFzZTVmIn0seyJhY3Rpb24iOiJSRURVQ0VfQ1VSUkVOVCIsImNvbmRpdGlvbiI6eyJsZWZ0IjoicDVmX3JzaSIsIm9wIjoiY3Jvc3NfYWJvdmUiLCJyaWdodCI6NTB9LCJmcmFjdGlvbiI6MC41LCJyZWFzb24iOiJwaGFzZTVmIn0seyJhY3Rpb24iOiJFTlRFUl9MT05HIiwiY29uZGl0aW9uIjp7ImFyZ3MiOlt7Im9wIjoicHVsc2UiLCJ2YWx1ZSI6InA1Zl9sb3dlcl9mcmFjdGFsIn0seyJkaXJlY3Rpb24iOiJidWxsaXNoIiwiZXZlbnRfaWQiOiJwNWZfcnNpX2J1bGxpc2giLCJpbmRpY2F0b3IiOiJwNWZfcnNpIiwibG9va2JhY2siOjYwLCJvcCI6InJlZ3VsYXJfZGl2ZXJnZW5jZSIsInByaWNlIjoicDVmX2xvdyIsInNpZGVfYmFycyI6Mn1dLCJvcCI6ImFuZCJ9LCJmcmFjdGlvbiI6MS4wLCJyZWFzb24iOiJwaGFzZTVmIn0seyJhY3Rpb24iOiJFTlRFUl9TSE9SVCIsImNvbmRpdGlvbiI6eyJhcmdzIjpbeyJvcCI6InB1bHNlIiwidmFsdWUiOiJwNWZfdXBwZXJfZnJhY3RhbCJ9LHsiZGlyZWN0aW9uIjoiYmVhcmlzaCIsImV2ZW50X2lkIjoicDVmX3JzaV9iZWFyaXNoIiwiaW5kaWNhdG9yIjoicDVmX3JzaSIsImxvb2tiYWNrIjo2MCwib3AiOiJyZWd1bGFyX2RpdmVyZ2VuY2UiLCJwcmljZSI6InA1Zl9oaWdoIiwic2lkZV9iYXJzIjoyfV0sIm9wIjoiYW5kIn0sImZyYWN0aW9uIjoxLjAsInJlYXNvbiI6InBoYXNlNWYifV0sImZhbWlseSI6IlA1Rl9SU0lfRlJBQ1RBTF9ESVZFUkdFTkNFIiwiZmVhdHVyZXMiOlt7ImZpZWxkIjoiY2xvc2UiLCJraW5kIjoiYmFyIiwibmFtZSI6InA1Zl9jbG9zZSJ9LHsiZmllbGQiOiJoaWdoIiwia2luZCI6ImJhciIsIm5hbWUiOiJwNWZfaGlnaCJ9LHsiZmllbGQiOiJsb3ciLCJraW5kIjoiYmFyIiwibmFtZSI6InA1Zl9sb3cifSx7ImZpZWxkIjoidm9sdW1lIiwia2luZCI6ImJhciIsIm5hbWUiOiJwNWZfdm9sdW1lIn0seyJraW5kIjoicnNpIiwibmFtZSI6InA1Zl9yc2kiLCJ3aW5kb3ciOjE0fSx7ImtpbmQiOiJmcmFjdGFsIiwibmFtZSI6InA1Zl9sb3dlcl9mcmFjdGFsIiwib3V0cHV0IjoibG93ZXJfcHVsc2UifSx7ImtpbmQiOiJmcmFjdGFsIiwibmFtZSI6InA1Zl91cHBlcl9mcmFjdGFsIiwib3V0cHV0IjoidXBwZXJfcHVsc2UifV0sInNjaGVtYV92ZXJzaW9uIjoyLCJzb3VyY2VfY2xhdXNlX2NvdW50IjozfQ=='
    contract_versions: str = 'MODELLED_STANDARD_REGULAR_DIVERGENCE_V1;CONFIRMED_FRACTAL_2X2_V1;DIVERGENCE_LOOKBACK_60_V1;ACTION_PRECEDENCE_EXIT_REDUCE_ENTER_V1;REDUCE_HALF_CURRENT_V1'
