"""Typed configuration compiled from workbook row xlsx_s2_0840."""

from dataclasses import dataclass

from strategies.workbook_parametric.config import WorkbookParametricConfig


@dataclass(frozen=True)
class XlsxS20840Config(WorkbookParametricConfig):
    source_registry_id: str = 'xlsx_s2_0840'
    family: str = 'phase5b_declarative'
    semantic_provenance: str = 'STANDARD_CONTRACT_RESOLVED'
    contracts_applied: str = 'PREVIOUS_COMMITTED_STATE_V1;REDUCE_HALF_CURRENT_V1'
    defaulted_parameters: str = ''
    rule_spec_b64: str = 'eyJhY3Rpb25zIjpbeyJhY3Rpb24iOiJFWElUX0xPTkciLCJjb25kaXRpb24iOnsibGVmdCI6InA1Yl9kaWYiLCJvcCI6ImNyb3NzX2JlbG93IiwicmlnaHQiOjAuMH0sImZyYWN0aW9uIjoxLjAsInJlYXNvbiI6InBoYXNlNWIifSx7ImFjdGlvbiI6IkVYSVRfU0hPUlQiLCJjb25kaXRpb24iOnsibGVmdCI6InA1Yl9kaWYiLCJvcCI6ImNyb3NzX2Fib3ZlIiwicmlnaHQiOjAuMH0sImZyYWN0aW9uIjoxLjAsInJlYXNvbiI6InBoYXNlNWIifSx7ImFjdGlvbiI6IlJFRFVDRV9DVVJSRU5UIiwiY29uZGl0aW9uIjp7ImJhcnMiOjIsIm9wIjoiZmFsbGluZyIsInZhbHVlIjoicDViX2hpc3QifSwiZnJhY3Rpb24iOjAuNSwicmVhc29uIjoicGhhc2U1YiJ9LHsiYWN0aW9uIjoiRU5URVJfTE9ORyIsImNvbmRpdGlvbiI6eyJhcmdzIjpbeyJsZWZ0IjoicDViX2RpZiIsIm9wIjoiY3Jvc3NfYWJvdmUiLCJyaWdodCI6InA1Yl9kZWEifSx7ImxlZnQiOiJwNWJfaGlzdCIsIm9wIjoiZ3QiLCJyaWdodCI6MC4wfSx7ImJhcnMiOjEsIm9wIjoicmlzaW5nIiwidmFsdWUiOiJwNWJfaGlzdCJ9XSwib3AiOiJhbmQifSwiZnJhY3Rpb24iOjEuMCwicmVhc29uIjoicGhhc2U1YiJ9LHsiYWN0aW9uIjoiRU5URVJfU0hPUlQiLCJjb25kaXRpb24iOnsiYXJncyI6W3sibGVmdCI6InA1Yl9kaWYiLCJvcCI6ImNyb3NzX2JlbG93IiwicmlnaHQiOiJwNWJfZGVhIn0seyJsZWZ0IjoicDViX2hpc3QiLCJvcCI6Imx0IiwicmlnaHQiOjAuMH0seyJiYXJzIjoxLCJvcCI6ImZhbGxpbmciLCJ2YWx1ZSI6InA1Yl9oaXN0In1dLCJvcCI6ImFuZCJ9LCJmcmFjdGlvbiI6MS4wLCJyZWFzb24iOiJwaGFzZTViIn1dLCJmYW1pbHkiOiJNQUNEX0hJU1RPR1JBTV9DT05GSVJNQVRJT04iLCJmZWF0dXJlcyI6W3siZmllbGQiOiJjbG9zZSIsImtpbmQiOiJiYXIiLCJuYW1lIjoicDViX2Nsb3NlIn0seyJmaWVsZCI6Im9wZW4iLCJraW5kIjoiYmFyIiwibmFtZSI6InA1Yl9vcGVuIn0seyJraW5kIjoibWFjZCIsIm5hbWUiOiJwNWJfZGlmIiwib3V0cHV0IjoiZGlmIn0seyJraW5kIjoibWFjZCIsIm5hbWUiOiJwNWJfZGVhIiwib3V0cHV0Ijoic2lnbmFsIn0seyJraW5kIjoibWFjZCIsIm5hbWUiOiJwNWJfaGlzdCIsIm91dHB1dCI6Imhpc3RvZ3JhbSJ9XSwic2NoZW1hX3ZlcnNpb24iOjIsInNvdXJjZV9jbGF1c2VfY291bnQiOjN9'
    contract_versions: str = 'PREVIOUS_COMMITTED_STATE_V1;REDUCE_HALF_CURRENT_V1'
