"""Typed configuration compiled from workbook row xlsx_s2_0364."""

from dataclasses import dataclass

from strategies.workbook_parametric.config import WorkbookParametricConfig


@dataclass(frozen=True)
class XlsxS20364Config(WorkbookParametricConfig):
    source_registry_id: str = 'xlsx_s2_0364'
    family: str = 'phase5a_declarative'
    semantic_provenance: str = 'PARAMETER_DEFAULTED'
    contracts_applied: str = 'CONFLUENCE_AND_V1;LAYERED_REDUCTION_EQUAL_V1'
    defaulted_parameters: str = 'reduction_fraction=0.5'
    rule_spec_b64: str = 'eyJleGl0X2xvbmciOnsibGVmdCI6InA1X2FkeF8xNCIsIm9wIjoibHQiLCJyaWdodCI6MjAuMH0sImV4aXRfc2hvcnQiOnsibGVmdCI6InA1X2FkeF8xNCIsIm9wIjoibHQiLCJyaWdodCI6MjAuMH0sImZlYXR1cmVzIjpbeyJmaWVsZCI6ImNsb3NlIiwia2luZCI6ImJhciIsIm5hbWUiOiJwNV9jbG9zZSJ9LHsiZmllbGQiOiJvcGVuIiwia2luZCI6ImJhciIsIm5hbWUiOiJwNV9vcGVuIn0seyJraW5kIjoiYWR4IiwibmFtZSI6InA1X2FkeF8xNCIsIndpbmRvdyI6MTR9LHsia2luZCI6InNtYSIsIm5hbWUiOiJwNV9zbWFfMjAiLCJ3aW5kb3ciOjIwfSx7ImtpbmQiOiJzbWEiLCJuYW1lIjoicDVfc21hXzYwIiwid2luZG93Ijo2MH1dLCJsb25nIjp7ImFyZ3MiOlt7ImxlZnQiOiJwNV9hZHhfMTQiLCJvcCI6Imd0IiwicmlnaHQiOjI1LjB9LHsibGVmdCI6InA1X3NtYV8yMCIsIm9wIjoiY3Jvc3NfYWJvdmUiLCJyaWdodCI6InA1X3NtYV82MCJ9XSwib3AiOiJhbmQifSwicmVkdWNlX2xvbmciOnsibGVmdCI6InA1X3NtYV8yMCIsIm9wIjoiY3Jvc3NfYmVsb3ciLCJyaWdodCI6InA1X3NtYV82MCJ9LCJyZWR1Y2Vfc2hvcnQiOnsibGVmdCI6InA1X3NtYV8yMCIsIm9wIjoiY3Jvc3NfYWJvdmUiLCJyaWdodCI6InA1X3NtYV82MCJ9LCJyZWR1Y3Rpb25fZnJhY3Rpb24iOjAuNSwic2NoZW1hX3ZlcnNpb24iOjEsInNob3J0Ijp7ImFyZ3MiOlt7ImxlZnQiOiJwNV9hZHhfMTQiLCJvcCI6Imd0IiwicmlnaHQiOjI1LjB9LHsibGVmdCI6InA1X3NtYV8yMCIsIm9wIjoiY3Jvc3NfYmVsb3ciLCJyaWdodCI6InA1X3NtYV82MCJ9XSwib3AiOiJhbmQifX0='
    contract_versions: str = 'CONFLUENCE_AND_V1;LAYERED_REDUCTION_EQUAL_V1'
    modelled_interpretations: str = ''
