"""Typed configuration compiled from workbook row xlsx_s2_0240."""

from dataclasses import dataclass

from strategies.workbook_parametric.config import WorkbookParametricConfig


@dataclass(frozen=True)
class XlsxS20240Config(WorkbookParametricConfig):
    source_registry_id: str = 'xlsx_s2_0240'
    family: str = 'phase5b_declarative'
    semantic_provenance: str = 'STANDARD_CONTRACT_RESOLVED'
    contracts_applied: str = 'VOLATILITY_EXPANSION_RELATIVE_SMA20_V1;VOLATILITY_CONTRACTION_RELATIVE_SMA20_V1'
    defaulted_parameters: str = ''
    rule_spec_b64: str = 'eyJhY3Rpb25zIjpbeyJhY3Rpb24iOiJFWElUX0FMTCIsImNvbmRpdGlvbiI6eyJsZWZ0IjoicDVjX2JidyIsIm9wIjoibHQiLCJyaWdodCI6eyJvcCI6InJvbGxpbmdfbWVhbiIsInZhbHVlIjoicDVjX2JidyIsIndpbmRvdyI6MjB9fSwiZnJhY3Rpb24iOjEuMCwicmVhc29uIjoicGhhc2U1YyJ9LHsiYWN0aW9uIjoiRU5URVJfTE9ORyIsImNvbmRpdGlvbiI6eyJhcmdzIjpbeyJvcCI6InBvc2l0aW9uX2lzIiwic2lkZSI6ImZsYXQifSx7ImxlZnQiOiJwNWNfYmJ3Iiwib3AiOiJndCIsInJpZ2h0Ijp7Im9wIjoicm9sbGluZ19tZWFuIiwidmFsdWUiOiJwNWNfYmJ3Iiwid2luZG93IjoyMH19LHsib3AiOiJwdWxzZSIsInZhbHVlIjoicDVjX3VwIn1dLCJvcCI6ImFuZCJ9LCJmcmFjdGlvbiI6MS4wLCJyZWFzb24iOiJwaGFzZTVjIn0seyJhY3Rpb24iOiJFTlRFUl9TSE9SVCIsImNvbmRpdGlvbiI6eyJhcmdzIjpbeyJvcCI6InBvc2l0aW9uX2lzIiwic2lkZSI6ImZsYXQifSx7ImxlZnQiOiJwNWNfYmJ3Iiwib3AiOiJndCIsInJpZ2h0Ijp7Im9wIjoicm9sbGluZ19tZWFuIiwidmFsdWUiOiJwNWNfYmJ3Iiwid2luZG93IjoyMH19LHsib3AiOiJwdWxzZSIsInZhbHVlIjoicDVjX2Rvd24ifV0sIm9wIjoiYW5kIn0sImZyYWN0aW9uIjoxLjAsInJlYXNvbiI6InBoYXNlNWMifV0sImZhbWlseSI6IkRPTkNISUFOX0JCV19GSUxURVIiLCJmZWF0dXJlcyI6W3siZmllbGQiOiJjbG9zZSIsImtpbmQiOiJiYXIiLCJuYW1lIjoicDVjX2Nsb3NlIn0seyJmaWVsZCI6Im9wZW4iLCJraW5kIjoiYmFyIiwibmFtZSI6InA1Y19vcGVuIn0seyJmaWVsZCI6ImhpZ2giLCJraW5kIjoiYmFyIiwibmFtZSI6InA1Y19oaWdoIn0seyJmaWVsZCI6ImxvdyIsImtpbmQiOiJiYXIiLCJuYW1lIjoicDVjX2xvdyJ9LHsia2luZCI6ImJvbGxpbmdlcl93aWR0aCIsIm5hbWUiOiJwNWNfYmJ3Iiwid2luZG93IjoyMH0seyJraW5kIjoiYnJlYWtvdXRfdXAiLCJuYW1lIjoicDVjX3VwIiwid2luZG93IjoyMH0seyJraW5kIjoiYnJlYWtvdXRfZG93biIsIm5hbWUiOiJwNWNfZG93biIsIndpbmRvdyI6MjB9XSwic2NoZW1hX3ZlcnNpb24iOjIsInNvdXJjZV9jbGF1c2VfY291bnQiOjN9'
    contract_versions: str = 'VOLATILITY_EXPANSION_RELATIVE_SMA20_V1;VOLATILITY_CONTRACTION_RELATIVE_SMA20_V1'
