"""Typed configuration compiled from workbook row xlsx_s2_0846."""

from dataclasses import dataclass

from strategies.workbook_parametric.config import WorkbookParametricConfig


@dataclass(frozen=True)
class XlsxS20846Config(WorkbookParametricConfig):
    source_registry_id: str = 'xlsx_s2_0846'
    family: str = 'phase5b_declarative'
    semantic_provenance: str = 'STANDARD_CONTRACT_RESOLVED'
    contracts_applied: str = 'STABILIZE_MINIMAL_TRANSITION_V1;TURN_SLOPE_SIGN_CHANGE_V1;REDUCE_HALF_CURRENT_V1'
    defaulted_parameters: str = ''
    rule_spec_b64: str = 'eyJhY3Rpb25zIjpbeyJhY3Rpb24iOiJFWElUX0xPTkciLCJjb25kaXRpb24iOnsibGVmdCI6InA1Y19yb2MiLCJvcCI6ImNyb3NzX2JlbG93IiwicmlnaHQiOjAuMH0sImZyYWN0aW9uIjoxLjAsInJlYXNvbiI6InBoYXNlNWMifSx7ImFjdGlvbiI6IkVYSVRfU0hPUlQiLCJjb25kaXRpb24iOnsibGVmdCI6InA1Y19yb2MiLCJvcCI6ImNyb3NzX2Fib3ZlIiwicmlnaHQiOjAuMH0sImZyYWN0aW9uIjoxLjAsInJlYXNvbiI6InBoYXNlNWMifSx7ImFjdGlvbiI6IlJFRFVDRV9MT05HIiwiY29uZGl0aW9uIjp7ImxlZnQiOiJwNWNfcHJpbWFyeSIsIm9wIjoiY3Jvc3NfYWJvdmUiLCJyaWdodCI6MC4wfSwiZnJhY3Rpb24iOjAuNSwicmVhc29uIjoicGhhc2U1YyJ9LHsiYWN0aW9uIjoiUkVEVUNFX1NIT1JUIiwiY29uZGl0aW9uIjp7ImxlZnQiOiJwNWNfcHJpbWFyeSIsIm9wIjoiY3Jvc3NfYmVsb3ciLCJyaWdodCI6MC4wfSwiZnJhY3Rpb24iOjAuNSwicmVhc29uIjoicGhhc2U1YyJ9LHsiYWN0aW9uIjoiRU5URVJfTE9ORyIsImNvbmRpdGlvbiI6eyJhcmdzIjpbeyJvcCI6InBvc2l0aW9uX2lzIiwic2lkZSI6ImZsYXQifSx7ImxlZnQiOiJwNWNfcHJpbWFyeSIsIm9wIjoibHQiLCJyaWdodCI6LTEwMC4wfSx7ImxlZnQiOiJwNWNfcm9jIiwib3AiOiJsdCIsInJpZ2h0IjowLjB9LHsib3AiOiJ0dXJuX3VwIiwidmFsdWUiOiJwNWNfcm9jIn1dLCJvcCI6ImFuZCJ9LCJmcmFjdGlvbiI6MS4wLCJyZWFzb24iOiJwaGFzZTVjIn0seyJhY3Rpb24iOiJFTlRFUl9TSE9SVCIsImNvbmRpdGlvbiI6eyJhcmdzIjpbeyJvcCI6InBvc2l0aW9uX2lzIiwic2lkZSI6ImZsYXQifSx7ImxlZnQiOiJwNWNfcHJpbWFyeSIsIm9wIjoiZ3QiLCJyaWdodCI6MTAwLjB9LHsibGVmdCI6InA1Y19yb2MiLCJvcCI6Imd0IiwicmlnaHQiOjAuMH0seyJvcCI6InR1cm5fZG93biIsInZhbHVlIjoicDVjX3JvYyJ9XSwib3AiOiJhbmQifSwiZnJhY3Rpb24iOjEuMCwicmVhc29uIjoicGhhc2U1YyJ9XSwiZmFtaWx5IjoiQ0NJX1JPQ19TVEFCSUxJWkVEX1JFVkVSU0FMIiwiZmVhdHVyZXMiOlt7ImZpZWxkIjoiY2xvc2UiLCJraW5kIjoiYmFyIiwibmFtZSI6InA1Y19jbG9zZSJ9LHsiZmllbGQiOiJvcGVuIiwia2luZCI6ImJhciIsIm5hbWUiOiJwNWNfb3BlbiJ9LHsiZmllbGQiOiJoaWdoIiwia2luZCI6ImJhciIsIm5hbWUiOiJwNWNfaGlnaCJ9LHsiZmllbGQiOiJsb3ciLCJraW5kIjoiYmFyIiwibmFtZSI6InA1Y19sb3cifSx7ImtpbmQiOiJjY2kiLCJuYW1lIjoicDVjX3ByaW1hcnkiLCJ3aW5kb3ciOjIwfSx7ImtpbmQiOiJyZXR1cm4iLCJuYW1lIjoicDVjX3JvYyIsIndpbmRvdyI6MTJ9XSwic2NoZW1hX3ZlcnNpb24iOjIsInNvdXJjZV9jbGF1c2VfY291bnQiOjN9'
    contract_versions: str = 'STABILIZE_MINIMAL_TRANSITION_V1;TURN_SLOPE_SIGN_CHANGE_V1;REDUCE_HALF_CURRENT_V1'
