"""Typed configuration compiled from workbook row xlsx_s2_0862."""

from dataclasses import dataclass

from strategies.workbook_parametric.config import WorkbookParametricConfig


@dataclass(frozen=True)
class XlsxS20862Config(WorkbookParametricConfig):
    source_registry_id: str = 'xlsx_s2_0862'
    family: str = 'phase5a_declarative'
    semantic_provenance: str = 'MODELLED_BASELINE_INTERPRETATION'
    contracts_applied: str = 'MODELLED_VOLUME_REFERENCE_SMA20_V1;REDUCE_HALF_CURRENT_V1'
    defaulted_parameters: str = 'volume_lookback=20;reduction_fraction=0.5'
    rule_spec_b64: str = 'eyJleGl0X2xvbmciOnsibGVmdCI6InA1X2VtYV8xMCIsIm9wIjoiY3Jvc3NfYmVsb3ciLCJyaWdodCI6InA1X2VtYV8zMCJ9LCJleGl0X3Nob3J0Ijp7ImxlZnQiOiJwNV9lbWFfMTAiLCJvcCI6ImNyb3NzX2Fib3ZlIiwicmlnaHQiOiJwNV9lbWFfMzAifSwiZmVhdHVyZXMiOlt7ImZpZWxkIjoiY2xvc2UiLCJraW5kIjoiYmFyIiwibmFtZSI6InA1X2Nsb3NlIn0seyJmaWVsZCI6Im9wZW4iLCJraW5kIjoiYmFyIiwibmFtZSI6InA1X29wZW4ifSx7ImtpbmQiOiJlbWEiLCJuYW1lIjoicDVfZW1hXzEwIiwid2luZG93IjoxMH0seyJraW5kIjoiZW1hIiwibmFtZSI6InA1X2VtYV8zMCIsIndpbmRvdyI6MzB9LHsia2luZCI6InZvbHVtZV9yYXRpbyIsIm5hbWUiOiJwNV92b2x1bWVfcmF0aW9fMjAiLCJ3aW5kb3ciOjIwfV0sImxvbmciOnsiYXJncyI6W3sibGVmdCI6InA1X2VtYV8xMCIsIm9wIjoiY3Jvc3NfYWJvdmUiLCJyaWdodCI6InA1X2VtYV8zMCJ9LHsibGVmdCI6InA1X3ZvbHVtZV9yYXRpb18yMCIsIm9wIjoiZ3RlIiwicmlnaHQiOjIuMH1dLCJvcCI6ImFuZCJ9LCJyZWR1Y2VfbG9uZyI6eyJsZWZ0IjoicDVfdm9sdW1lX3JhdGlvXzIwIiwib3AiOiJsdCIsInJpZ2h0IjoxLjB9LCJyZWR1Y2Vfc2hvcnQiOnsibGVmdCI6InA1X3ZvbHVtZV9yYXRpb18yMCIsIm9wIjoibHQiLCJyaWdodCI6MS4wfSwicmVkdWN0aW9uX2ZyYWN0aW9uIjowLjUsInNjaGVtYV92ZXJzaW9uIjoxLCJzaG9ydCI6eyJhcmdzIjpbeyJsZWZ0IjoicDVfZW1hXzEwIiwib3AiOiJjcm9zc19iZWxvdyIsInJpZ2h0IjoicDVfZW1hXzMwIn0seyJsZWZ0IjoicDVfdm9sdW1lX3JhdGlvXzIwIiwib3AiOiJndGUiLCJyaWdodCI6Mi4wfV0sIm9wIjoiYW5kIn19'
    contract_versions: str = 'MODELLED_VOLUME_REFERENCE_SMA20_V1;REDUCE_HALF_CURRENT_V1'
    modelled_interpretations: str = 'MODELLED_VOLUME_REFERENCE_SMA20_V1'
