from nautilus_ext.instruments.instrument_profile import InstrumentProfile


INSTRUMENT_METADATA_REQUIREMENTS = {
    "crypto_perpetual": [
        "instrument_id",
        "raw_symbol",
        "base_currency",
        "quote_currency",
        "settlement_currency",
        "price_precision",
        "size_precision",
        "price_increment",
        "size_increment",
        "maker_fee",
        "taker_fee",
        "margin_init",
        "margin_maint",
    ],
    "currency_pair": [
        "instrument_id",
        "raw_symbol",
        "base_currency",
        "quote_currency",
        "price_precision",
        "size_precision",
        "price_increment",
        "size_increment",
    ],
    "equity": [
        "instrument_id",
        "raw_symbol",
        "venue",
        "currency",
        "price_precision",
        "size_precision",
        "price_increment",
        "size_increment",
    ],
    "futures_contract": [
        "instrument_id",
        "raw_symbol",
        "underlying",
        "currency",
        "settlement_currency",
        "expiry",
        "multiplier",
        "price_precision",
        "size_precision",
        "price_increment",
        "size_increment",
    ],
    "crypto_future": [
        "instrument_id",
        "raw_symbol",
        "base_currency",
        "quote_currency",
        "settlement_currency",
        "expiry",
        "price_precision",
        "size_precision",
        "price_increment",
        "size_increment",
    ],
    "option_contract": [
        "instrument_id",
        "raw_symbol",
        "underlying",
        "currency",
        "expiry",
        "strike_price",
        "option_kind",
        "price_precision",
        "size_precision",
        "price_increment",
        "size_increment",
    ],
    "crypto_option": [
        "instrument_id",
        "raw_symbol",
        "underlying",
        "base_currency",
        "quote_currency",
        "settlement_currency",
        "expiry",
        "strike_price",
        "option_kind",
        "price_precision",
        "size_precision",
        "price_increment",
        "size_increment",
    ],
    "cfd": [
        "instrument_id",
        "raw_symbol",
        "underlying",
        "currency",
        "price_precision",
        "size_precision",
        "price_increment",
        "size_increment",
    ],
    "commodity": [
        "instrument_id",
        "raw_symbol",
        "currency",
        "price_precision",
        "size_precision",
        "price_increment",
        "size_increment",
    ],
    "index": [
        "instrument_id",
        "raw_symbol",
        "currency",
        "price_precision",
        "price_increment",
    ],
    "synthetic": [
        "instrument_id",
        "raw_symbol",
        "synthetic_formula",
        "components",
        "price_precision",
        "price_increment",
    ],
    "futures_spread": ["instrument_id", "raw_symbol", "components"],
    "option_spread": ["instrument_id", "raw_symbol", "components"],
    "binary_option": ["instrument_id", "raw_symbol", "underlying", "expiry"],
    "betting": ["instrument_id", "raw_symbol", "underlying"],
    "perpetual_contract": [
        "instrument_id",
        "raw_symbol",
        "underlying",
        "quote_currency",
        "settlement_currency",
        "price_precision",
        "size_precision",
        "price_increment",
        "size_increment",
    ],
    "unknown": [],
}


def required_fields_for(instrument_type: str) -> list[str]:
    return list(INSTRUMENT_METADATA_REQUIREMENTS.get(instrument_type, []))


def missing_fields_for_profile(profile: InstrumentProfile) -> list[str]:
    return profile.missing_required_fields(required_fields_for(profile.instrument_type))
