"""Typed configuration compiled from workbook row xlsx_s2_0278."""

from dataclasses import dataclass

from strategies.workbook_parametric.config import WorkbookParametricConfig


@dataclass(frozen=True)
class XlsxS20278Config(WorkbookParametricConfig):
    source_registry_id: str = 'xlsx_s2_0278'
    family: str = 'phase5b_declarative'
    semantic_provenance: str = 'STANDARD_CONTRACT_RESOLVED'
    contracts_applied: str = 'REDUCE_HALF_CURRENT_V1;ACTION_PRECEDENCE_EXIT_REDUCE_ENTER_V1'
    defaulted_parameters: str = ''
    rule_spec_b64: str = 'eyJhY3Rpb25zIjpbeyJhY3Rpb24iOiJFWElUX0FMTCIsImNvbmRpdGlvbiI6eyJsZWZ0IjoicDViX2FkeDE0Iiwib3AiOiJsdCIsInJpZ2h0IjoyMC4wfSwiZnJhY3Rpb24iOjEuMCwicmVhc29uIjoicGhhc2U1YiJ9LHsiYWN0aW9uIjoiUkVEVUNFX0NVUlJFTlQiLCJjb25kaXRpb24iOnsiYXJncyI6W3sibGVmdCI6InA1Yl9tYTIwIiwib3AiOiJjcm9zc19iZWxvdyIsInJpZ2h0IjoicDViX21hNjAifSx7ImxlZnQiOiJwNWJfbWEyMCIsIm9wIjoiY3Jvc3NfYWJvdmUiLCJyaWdodCI6InA1Yl9tYTYwIn1dLCJvcCI6Im9yIn0sImZyYWN0aW9uIjowLjUsInJlYXNvbiI6InBoYXNlNWIifSx7ImFjdGlvbiI6IkVOVEVSX0xPTkciLCJjb25kaXRpb24iOnsiYXJncyI6W3sibGVmdCI6InA1Yl9hZHgxNCIsIm9wIjoiZ3QiLCJyaWdodCI6MjUuMH0seyJsZWZ0IjoicDViX21hMjAiLCJvcCI6ImNyb3NzX2Fib3ZlIiwicmlnaHQiOiJwNWJfbWE2MCJ9XSwib3AiOiJhbmQifSwiZnJhY3Rpb24iOjEuMCwicmVhc29uIjoicGhhc2U1YiJ9LHsiYWN0aW9uIjoiRU5URVJfU0hPUlQiLCJjb25kaXRpb24iOnsiYXJncyI6W3sibGVmdCI6InA1Yl9hZHgxNCIsIm9wIjoiZ3QiLCJyaWdodCI6MjUuMH0seyJsZWZ0IjoicDViX21hMjAiLCJvcCI6ImNyb3NzX2JlbG93IiwicmlnaHQiOiJwNWJfbWE2MCJ9XSwib3AiOiJhbmQifSwiZnJhY3Rpb24iOjEuMCwicmVhc29uIjoicGhhc2U1YiJ9XSwiZmFtaWx5IjoiQURYX0RVQUxfTUEiLCJmZWF0dXJlcyI6W3siZmllbGQiOiJjbG9zZSIsImtpbmQiOiJiYXIiLCJuYW1lIjoicDViX2Nsb3NlIn0seyJmaWVsZCI6Im9wZW4iLCJraW5kIjoiYmFyIiwibmFtZSI6InA1Yl9vcGVuIn0seyJraW5kIjoiYWR4IiwibmFtZSI6InA1Yl9hZHgxNCIsIndpbmRvdyI6MTR9LHsia2luZCI6InNtYSIsIm5hbWUiOiJwNWJfbWEyMCIsIndpbmRvdyI6MjB9LHsia2luZCI6InNtYSIsIm5hbWUiOiJwNWJfbWE2MCIsIndpbmRvdyI6NjB9XSwic2NoZW1hX3ZlcnNpb24iOjIsInNvdXJjZV9jbGF1c2VfY291bnQiOjN9'
    contract_versions: str = 'REDUCE_HALF_CURRENT_V1;ACTION_PRECEDENCE_EXIT_REDUCE_ENTER_V1'
