from nautilus_ext.instruments.instrument_profile import InstrumentProfile


def load_profiles() -> list[InstrumentProfile]:
    return [
        InstrumentProfile(
            symbol="BTC-20240628-70000-C",
            venue="DERIBIT",
            instrument_type="crypto_option",
            instrument_id="BTC-20240628-70000-C.DERIBIT",
            raw_symbol="BTC-20240628-70000-C",
            base_currency="BTC",
            quote_currency="USD",
            settlement_currency="BTC",
            asset_class="crypto",
            underlying="BTC",
            expiry="2024-06-28",
            strike_price="70000",
            option_kind="CALL",
            price_precision=2,
            size_precision=4,
            price_increment="0.01",
            size_increment="0.0001",
            source="registry:options",
            confidence=0.4,
            metadata={
                "required_fields": [
                    "underlying",
                    "expiry",
                    "strike_price",
                    "option_kind",
                ],
            },
        ),
        InstrumentProfile(
            symbol="AAPL-20250117-200-C",
            venue="OPRA",
            instrument_type="option_contract",
            instrument_id="AAPL-20250117-200-C.OPRA",
            raw_symbol="AAPL-20250117-200-C",
            underlying="AAPL",
            currency="USD",
            asset_class="equity",
            expiry="2025-01-17",
            strike_price="200",
            option_kind="CALL",
            price_precision=2,
            size_precision=0,
            price_increment="0.01",
            size_increment="1",
            source="registry:options",
            confidence=0.35,
            metadata={"note": "Example option profile; verify production metadata."},
        ),
    ]
