"""Typed configuration compiled from workbook row xlsx_s2_0353."""

from dataclasses import dataclass

from strategies.workbook_parametric.config import WorkbookParametricConfig


@dataclass(frozen=True)
class XlsxS20353Config(WorkbookParametricConfig):
    source_registry_id: str = 'xlsx_s2_0353'
    family: str = 'phase5a_declarative'
    semantic_provenance: str = 'STANDARD_CONTRACT_RESOLVED'
    contracts_applied: str = 'BOUNDED_INDICATOR_EXTREMES_V1;CONFLUENCE_AND_V1'
    defaulted_parameters: str = ''
    rule_spec_b64: str = 'eyJleGl0X2xvbmciOnsiYXJncyI6W3sibGVmdCI6InA1X3JzaV81Iiwib3AiOiJjcm9zc19iZWxvdyIsInJpZ2h0IjoicDVfcnNpXzE0In0seyJsZWZ0IjoicDVfcnNpXzE0Iiwib3AiOiJndGUiLCJyaWdodCI6NzAuMH1dLCJvcCI6Im9yIn0sImV4aXRfc2hvcnQiOnsiYXJncyI6W3sibGVmdCI6InA1X3JzaV81Iiwib3AiOiJjcm9zc19hYm92ZSIsInJpZ2h0IjoicDVfcnNpXzE0In0seyJsZWZ0IjoicDVfcnNpXzE0Iiwib3AiOiJsdGUiLCJyaWdodCI6MzAuMH1dLCJvcCI6Im9yIn0sImZlYXR1cmVzIjpbeyJmaWVsZCI6ImNsb3NlIiwia2luZCI6ImJhciIsIm5hbWUiOiJwNV9jbG9zZSJ9LHsiZmllbGQiOiJvcGVuIiwia2luZCI6ImJhciIsIm5hbWUiOiJwNV9vcGVuIn0seyJraW5kIjoicnNpIiwibmFtZSI6InA1X3JzaV81Iiwid2luZG93Ijo1fSx7ImtpbmQiOiJyc2kiLCJuYW1lIjoicDVfcnNpXzE0Iiwid2luZG93IjoxNH1dLCJsb25nIjp7ImFyZ3MiOlt7ImxlZnQiOiJwNV9yc2lfNSIsIm9wIjoiY3Jvc3NfYWJvdmUiLCJyaWdodCI6InA1X3JzaV8xNCJ9LHsibGVmdCI6InA1X3JzaV8xNCIsIm9wIjoiZ3QiLCJyaWdodCI6NDAuMH1dLCJvcCI6ImFuZCJ9LCJzY2hlbWFfdmVyc2lvbiI6MSwic2hvcnQiOnsiYXJncyI6W3sibGVmdCI6InA1X3JzaV81Iiwib3AiOiJjcm9zc19iZWxvdyIsInJpZ2h0IjoicDVfcnNpXzE0In0seyJsZWZ0IjoicDVfcnNpXzE0Iiwib3AiOiJsdCIsInJpZ2h0Ijo2MC4wfV0sIm9wIjoiYW5kIn19'
    contract_versions: str = 'BOUNDED_INDICATOR_EXTREMES_V1;CONFLUENCE_AND_V1'
    modelled_interpretations: str = ''
