"""Typed configuration compiled from workbook row xlsx_s1_0504."""

from dataclasses import dataclass

from strategies.workbook_parametric.config import WorkbookParametricConfig


@dataclass(frozen=True)
class XlsxS10504Config(WorkbookParametricConfig):
    source_registry_id: str = 'xlsx_s1_0504'
    family: str = 'phase5b_declarative'
    semantic_provenance: str = 'STANDARD_CONTRACT_RESOLVED'
    contracts_applied: str = 'CONFIRMED_FRACTAL_2X2_V1;REDUCE_HALF_CURRENT_V1'
    defaulted_parameters: str = ''
    rule_spec_b64: str = 'eyJhY3Rpb25zIjpbeyJhY3Rpb24iOiJFWElUX0xPTkciLCJjb25kaXRpb24iOnsib3AiOiJwdWxzZSIsInZhbHVlIjoicDViX3VwcGVyIn0sImZyYWN0aW9uIjoxLjAsInJlYXNvbiI6InBoYXNlNWIifSx7ImFjdGlvbiI6IkVYSVRfU0hPUlQiLCJjb25kaXRpb24iOnsib3AiOiJwdWxzZSIsInZhbHVlIjoicDViX2xvd2VyIn0sImZyYWN0aW9uIjoxLjAsInJlYXNvbiI6InBoYXNlNWIifSx7ImFjdGlvbiI6IlJFRFVDRV9DVVJSRU5UIiwiY29uZGl0aW9uIjp7ImFyZ3MiOlt7ImxlZnQiOiJwNWJfYmlhczIwIiwib3AiOiJjcm9zc19hYm92ZSIsInJpZ2h0IjowLjB9LHsibGVmdCI6InA1Yl9iaWFzMjAiLCJvcCI6ImNyb3NzX2JlbG93IiwicmlnaHQiOjAuMH1dLCJvcCI6Im9yIn0sImZyYWN0aW9uIjowLjUsInJlYXNvbiI6InBoYXNlNWIifSx7ImFjdGlvbiI6IkVOVEVSX0xPTkciLCJjb25kaXRpb24iOnsiYXJncyI6W3sibGVmdCI6InA1Yl9iaWFzMjAiLCJvcCI6Imx0IiwicmlnaHQiOi03LjB9LHsib3AiOiJwdWxzZSIsInZhbHVlIjoicDViX2xvd2VyIn1dLCJvcCI6ImFuZCJ9LCJmcmFjdGlvbiI6MS4wLCJyZWFzb24iOiJwaGFzZTViIn0seyJhY3Rpb24iOiJFTlRFUl9TSE9SVCIsImNvbmRpdGlvbiI6eyJhcmdzIjpbeyJsZWZ0IjoicDViX2JpYXMyMCIsIm9wIjoiZ3QiLCJyaWdodCI6Ny4wfSx7Im9wIjoicHVsc2UiLCJ2YWx1ZSI6InA1Yl91cHBlciJ9XSwib3AiOiJhbmQifSwiZnJhY3Rpb24iOjEuMCwicmVhc29uIjoicGhhc2U1YiJ9XSwiZmFtaWx5IjoiQklBU19GUkFDVEFMX1JFVkVSU0FMIiwiZmVhdHVyZXMiOlt7ImZpZWxkIjoiY2xvc2UiLCJraW5kIjoiYmFyIiwibmFtZSI6InA1Yl9jbG9zZSJ9LHsiZmllbGQiOiJvcGVuIiwia2luZCI6ImJhciIsIm5hbWUiOiJwNWJfb3BlbiJ9LHsia2luZCI6ImJpYXMiLCJuYW1lIjoicDViX2JpYXMyMCIsIndpbmRvdyI6MjB9LHsia2luZCI6ImZyYWN0YWwiLCJuYW1lIjoicDViX2xvd2VyIiwib3V0cHV0IjoibG93ZXJfcHVsc2UifSx7ImtpbmQiOiJmcmFjdGFsIiwibmFtZSI6InA1Yl91cHBlciIsIm91dHB1dCI6InVwcGVyX3B1bHNlIn1dLCJzY2hlbWFfdmVyc2lvbiI6Miwic291cmNlX2NsYXVzZV9jb3VudCI6M30='
    contract_versions: str = 'CONFIRMED_FRACTAL_2X2_V1;REDUCE_HALF_CURRENT_V1'
