"""Typed configuration compiled from workbook row xlsx_s2_0036."""

from dataclasses import dataclass

from strategies.workbook_parametric.config import WorkbookParametricConfig


@dataclass(frozen=True)
class XlsxS20036Config(WorkbookParametricConfig):
    source_registry_id: str = 'xlsx_s2_0036'
    family: str = 'phase5b_declarative'
    semantic_provenance: str = 'STANDARD_CONTRACT_RESOLVED'
    contracts_applied: str = 'TURN_SLOPE_SIGN_CHANGE_V1;ACTION_PRECEDENCE_EXIT_REDUCE_ENTER_V1'
    defaulted_parameters: str = ''
    rule_spec_b64: str = 'eyJhY3Rpb25zIjpbeyJhY3Rpb24iOiJFWElUX0xPTkciLCJjb25kaXRpb24iOnsiYXJncyI6W3sibGVmdCI6InA1Yl9wc2FyX2RpciIsIm9wIjoibHQiLCJyaWdodCI6MC4wfSx7ImxlZnQiOiJwNWJfY2xvc2UiLCJvcCI6ImNyb3NzX2JlbG93IiwicmlnaHQiOiJwNWJfbWE2MCJ9XSwib3AiOiJvciJ9LCJmcmFjdGlvbiI6MS4wLCJyZWFzb24iOiJwaGFzZTViIn0seyJhY3Rpb24iOiJFWElUX1NIT1JUIiwiY29uZGl0aW9uIjp7ImFyZ3MiOlt7ImxlZnQiOiJwNWJfcHNhcl9kaXIiLCJvcCI6Imd0IiwicmlnaHQiOjAuMH0seyJsZWZ0IjoicDViX2Nsb3NlIiwib3AiOiJjcm9zc19hYm92ZSIsInJpZ2h0IjoicDViX21hNjAifV0sIm9wIjoib3IifSwiZnJhY3Rpb24iOjEuMCwicmVhc29uIjoicGhhc2U1YiJ9LHsiYWN0aW9uIjoiRU5URVJfTE9ORyIsImNvbmRpdGlvbiI6eyJhcmdzIjpbeyJsZWZ0IjoicDViX21hNjAiLCJvcCI6Imd0IiwicmlnaHQiOnsib3AiOiJwcmV2aW91cyIsInZhbHVlIjoicDViX21hNjAifX0seyJsZWZ0IjoicDViX2Nsb3NlIiwib3AiOiJndCIsInJpZ2h0IjoicDViX3BzYXIifV0sIm9wIjoiYW5kIn0sImZyYWN0aW9uIjoxLjAsInJlYXNvbiI6InBoYXNlNWIifSx7ImFjdGlvbiI6IkVOVEVSX1NIT1JUIiwiY29uZGl0aW9uIjp7ImFyZ3MiOlt7ImxlZnQiOiJwNWJfbWE2MCIsIm9wIjoibHQiLCJyaWdodCI6eyJvcCI6InByZXZpb3VzIiwidmFsdWUiOiJwNWJfbWE2MCJ9fSx7ImxlZnQiOiJwNWJfY2xvc2UiLCJvcCI6Imx0IiwicmlnaHQiOiJwNWJfcHNhciJ9XSwib3AiOiJhbmQifSwiZnJhY3Rpb24iOjEuMCwicmVhc29uIjoicGhhc2U1YiJ9XSwiZmFtaWx5IjoiUFNBUl9NQV9UUkVORCIsImZlYXR1cmVzIjpbeyJmaWVsZCI6ImNsb3NlIiwia2luZCI6ImJhciIsIm5hbWUiOiJwNWJfY2xvc2UifSx7ImZpZWxkIjoib3BlbiIsImtpbmQiOiJiYXIiLCJuYW1lIjoicDViX29wZW4ifSx7ImtpbmQiOiJzbWEiLCJuYW1lIjoicDViX21hNjAiLCJ3aW5kb3ciOjYwfSx7ImtpbmQiOiJwc2FyIiwibmFtZSI6InA1Yl9wc2FyIiwib3V0cHV0Ijoic2FyIn0seyJraW5kIjoicHNhciIsIm5hbWUiOiJwNWJfcHNhcl9kaXIiLCJvdXRwdXQiOiJkaXJlY3Rpb24ifV0sInNjaGVtYV92ZXJzaW9uIjoyLCJzb3VyY2VfY2xhdXNlX2NvdW50IjozfQ=='
    contract_versions: str = 'TURN_SLOPE_SIGN_CHANGE_V1;ACTION_PRECEDENCE_EXIT_REDUCE_ENTER_V1'
