"""Typed configuration compiled from workbook row xlsx_s2_0745."""

from dataclasses import dataclass

from strategies.workbook_parametric.config import WorkbookParametricConfig


@dataclass(frozen=True)
class XlsxS20745Config(WorkbookParametricConfig):
    source_registry_id: str = 'xlsx_s2_0745'
    family: str = 'phase5a_declarative'
    semantic_provenance: str = 'PARAMETER_DEFAULTED'
    contracts_applied: str = 'STABLE_CLOSE_2BAR_V1;REDUCE_HALF_CURRENT_V1'
    defaulted_parameters: str = 'persistence_bars=2;reduction_fraction=0.5'
    rule_spec_b64: str = 'eyJleGl0X2xvbmciOnsibGVmdCI6InA1X2NjaV8yMCIsIm9wIjoiZ3RlIiwicmlnaHQiOjEwMC4wfSwiZXhpdF9zaG9ydCI6eyJsZWZ0IjoicDVfY2NpXzIwIiwib3AiOiJsdGUiLCJyaWdodCI6LTEwMC4wfSwiZmVhdHVyZXMiOlt7ImZpZWxkIjoiY2xvc2UiLCJraW5kIjoiYmFyIiwibmFtZSI6InA1X2Nsb3NlIn0seyJmaWVsZCI6Im9wZW4iLCJraW5kIjoiYmFyIiwibmFtZSI6InA1X29wZW4ifSx7ImtpbmQiOiJjY2kiLCJuYW1lIjoicDVfY2NpXzIwIiwid2luZG93IjoyMH0seyJraW5kIjoic21hIiwibmFtZSI6InA1X3NtYV82MCIsIndpbmRvdyI6NjB9XSwibG9uZyI6eyJhcmdzIjpbeyJhcmciOnsibGVmdCI6InA1X2Nsb3NlIiwib3AiOiJndCIsInJpZ2h0IjoicDVfc21hXzYwIn0sImJhcnMiOjIsIm9wIjoiY29uc2VjdXRpdmUifSx7ImxlZnQiOiJwNV9jY2lfMjAiLCJvcCI6ImNyb3NzX2Fib3ZlIiwicmlnaHQiOi0xMDAuMH1dLCJvcCI6ImFuZCJ9LCJyZWR1Y2VfbG9uZyI6eyJsZWZ0IjoicDVfY2NpXzIwIiwib3AiOiJjcm9zc19iZWxvdyIsInJpZ2h0IjowLjB9LCJyZWR1Y2Vfc2hvcnQiOnsibGVmdCI6InA1X2NjaV8yMCIsIm9wIjoiY3Jvc3NfYWJvdmUiLCJyaWdodCI6MC4wfSwicmVkdWN0aW9uX2ZyYWN0aW9uIjowLjUsInNjaGVtYV92ZXJzaW9uIjoxLCJzaG9ydCI6eyJhcmdzIjpbeyJhcmciOnsibGVmdCI6InA1X2Nsb3NlIiwib3AiOiJsdCIsInJpZ2h0IjoicDVfc21hXzYwIn0sImJhcnMiOjIsIm9wIjoiY29uc2VjdXRpdmUifSx7ImxlZnQiOiJwNV9jY2lfMjAiLCJvcCI6ImNyb3NzX2JlbG93IiwicmlnaHQiOjEwMC4wfV0sIm9wIjoiYW5kIn19'
    contract_versions: str = 'STABLE_CLOSE_2BAR_V1;REDUCE_HALF_CURRENT_V1'
    modelled_interpretations: str = ''
