"""Typed configuration compiled from workbook row xlsx_s2_0594."""

from dataclasses import dataclass

from strategies.workbook_parametric.config import WorkbookParametricConfig


@dataclass(frozen=True)
class XlsxS20594Config(WorkbookParametricConfig):
    source_registry_id: str = 'xlsx_s2_0594'
    family: str = 'phase5b_declarative'
    semantic_provenance: str = 'STANDARD_CONTRACT_RESOLVED'
    contracts_applied: str = 'MTF_LATEST_COMPLETED_STATE_V1;MTF_STATE_TRIGGER_DISTINCTION_V1;REDUCE_HALF_CURRENT_V1'
    defaulted_parameters: str = ''
    rule_spec_b64: str = 'eyJhY3Rpb25zIjpbeyJhY3Rpb24iOiJFWElUX0xPTkciLCJjb25kaXRpb24iOnsibGVmdCI6InA1Yl9kX2NjaSIsIm9wIjoiZ3RlIiwicmlnaHQiOjEwMC4wfSwiZnJhY3Rpb24iOjEuMCwicmVhc29uIjoicGhhc2U1YiJ9LHsiYWN0aW9uIjoiRVhJVF9TSE9SVCIsImNvbmRpdGlvbiI6eyJsZWZ0IjoicDViX2RfY2NpIiwib3AiOiJsdGUiLCJyaWdodCI6LTEwMC4wfSwiZnJhY3Rpb24iOjEuMCwicmVhc29uIjoicGhhc2U1YiJ9LHsiYWN0aW9uIjoiUkVEVUNFX0NVUlJFTlQiLCJjb25kaXRpb24iOnsiYXJncyI6W3sibGVmdCI6InA1Yl9oNF9jY2kiLCJvcCI6ImNyb3NzX2JlbG93IiwicmlnaHQiOjAuMH0seyJsZWZ0IjoicDViX2g0X2NjaSIsIm9wIjoiY3Jvc3NfYWJvdmUiLCJyaWdodCI6MC4wfV0sIm9wIjoib3IifSwiZnJhY3Rpb24iOjAuNSwicmVhc29uIjoicGhhc2U1YiJ9LHsiYWN0aW9uIjoiRU5URVJfTE9ORyIsImNvbmRpdGlvbiI6eyJhcmdzIjpbeyJsZWZ0IjoicDViX2RfY2NpIiwib3AiOiJndGUiLCJyaWdodCI6LTEwMC4wfSx7ImxlZnQiOiJwNWJfZF9jY2kiLCJvcCI6Imx0ZSIsInJpZ2h0IjowLjB9LHsibGVmdCI6InA1Yl9oNF9jY2kiLCJvcCI6ImNyb3NzX2Fib3ZlIiwicmlnaHQiOi0xMDAuMH1dLCJvcCI6ImFuZCJ9LCJmcmFjdGlvbiI6MS4wLCJyZWFzb24iOiJwaGFzZTViIn0seyJhY3Rpb24iOiJFTlRFUl9TSE9SVCIsImNvbmRpdGlvbiI6eyJhcmdzIjpbeyJsZWZ0IjoicDViX2RfY2NpIiwib3AiOiJndGUiLCJyaWdodCI6MC4wfSx7ImxlZnQiOiJwNWJfZF9jY2kiLCJvcCI6Imx0ZSIsInJpZ2h0IjoxMDAuMH0seyJsZWZ0IjoicDViX2g0X2NjaSIsIm9wIjoiY3Jvc3NfYmVsb3ciLCJyaWdodCI6MTAwLjB9XSwib3AiOiJhbmQifSwiZnJhY3Rpb24iOjEuMCwicmVhc29uIjoicGhhc2U1YiJ9XSwiZmFtaWx5IjoiTVRGX0RBSUxZXzRIX0NDSSIsImZlYXR1cmVzIjpbeyJmaWVsZCI6ImNsb3NlIiwia2luZCI6ImJhciIsIm5hbWUiOiJwNWJfY2xvc2UifSx7ImZpZWxkIjoib3BlbiIsImtpbmQiOiJiYXIiLCJuYW1lIjoicDViX29wZW4ifSx7ImluZGljYXRvciI6ImNjaSIsImluZGljYXRvcl9wYXJhbXMiOnt9LCJraW5kIjoiY29tcGxldGVkX3RpbWVmcmFtZSIsIm5hbWUiOiJwNWJfZF9jY2kiLCJvdXRwdXQiOiJ2YWx1ZSIsInRpbWVmcmFtZV9taW51dGVzIjoxNDQwLCJ3aW5kb3ciOjIwfSx7ImluZGljYXRvciI6ImNjaSIsImluZGljYXRvcl9wYXJhbXMiOnt9LCJraW5kIjoiY29tcGxldGVkX3RpbWVmcmFtZSIsIm5hbWUiOiJwNWJfaDRfY2NpIiwib3V0cHV0IjoidmFsdWUiLCJ0aW1lZnJhbWVfbWludXRlcyI6MjQwLCJ3aW5kb3ciOjIwfV0sInNjaGVtYV92ZXJzaW9uIjoyLCJzb3VyY2VfY2xhdXNlX2NvdW50IjozfQ=='
    contract_versions: str = 'MTF_LATEST_COMPLETED_STATE_V1;MTF_STATE_TRIGGER_DISTINCTION_V1;REDUCE_HALF_CURRENT_V1'
